name: format
on:
  push:
    paths:
    - 'content/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14' ]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Cache node modules
        uses: actions/cache@v2.1.7
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: | 
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Setup node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install yarn
      - run: yarn install
      - run: yarn cleanup
      - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4.13.1
      with:
        commit_message: Update Post Markdown Data
        commit_author: GitHub Actions <actions@github.com>