name: format
on:
  push:
    paths:
      - 'content/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14']
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Cache node modules
        uses: actions/cache@v3.0.5
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Setup node
        uses: actions/setup-node@v3.3.0
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn cleanup
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          commit_message: Format Post Markdown Data
          commit_author: GitHub Actions <actions@github.com>
